'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace TesterVB

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Public Class PowerfulCSharpEditor

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PowerfulCSharpEditor", GetType(PowerfulCSharpEditor).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        Public Shared ReadOnly Property backward0_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backward0_16x16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property btInvisibleChars_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btInvisibleChars.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property btShowFoldingLines_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btShowFoldingLines.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property clImage_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("clImage.UserAddedColumn", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Public Shared ReadOnly Property clName_UserAddedColumn() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("clName.UserAddedColumn", resourceCulture)
                Return CType(obj, Boolean)
            End Get
        End Property

        Public Shared ReadOnly Property cmMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("cmMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property copyToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property cutToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cutToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property edit_padding_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-padding-top", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property forward_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward_16x16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property gotoButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gotoButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property ilAutocomplete_ImageStream() As System.Windows.Forms.ImageListStreamer
            Get
                Dim obj As Object = ResourceManager.GetObject("ilAutocomplete.ImageStream", resourceCulture)
                Return CType(obj, System.Windows.Forms.ImageListStreamer)
            End Get
        End Property

        Public Shared ReadOnly Property ilAutocomplete_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ilAutocomplete.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property layer__minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layer--minus", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property layer__plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layer--plus", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property msMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("msMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property newToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property ofdMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ofdMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property openToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property pasteToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasteToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property printToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property redo_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_16x16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property saveToolStripButton_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveToolStripButton.Image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public Shared ReadOnly Property sfdMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("sfdMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property ssMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ssMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property tmUpdateInterface_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tmUpdateInterface.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property tsMain_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("tsMain.TrayLocation", resourceCulture)
                Return CType(obj, System.Drawing.Point)
            End Get
        End Property

        Public Shared ReadOnly Property undo_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_16x16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
